[project]
name = "partial-pinata-debugger"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.pinata-governance]
path = "contracts/pinata-governance.clar"
depends_on = []

[contracts.pinata-verification]
path = "contracts/pinata-verification.clar"
depends_on = []

[contracts.pinata-registry]
path = "contracts/pinata-registry.clar"
depends_on = []

[contracts.pinata-rewards]
path = "contracts/pinata-rewards.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
